### ISSUE TITLE
Cracking web/telnet/ftp password?

### ISSUE THREAD

**Issue by raspiduino** [minhng99/iGate_GW040#1]
I remembered cracking this router's ftp password with some bruteforce software. It's a really common password. But when entered the ftp server, there isn't any useful commands there.

How about cracking telnet or web password? Did you found out the way? I have found on the internet that VNPT's router password is set to `vnpt@linenumber`. Is that true?

Really, I don't want to contact service to ask for password.

Thank you!

P/S: if cracking that password is easy then it's a real security issue for many VNPT users.

**Comment by raspiduino** [comment]
I have just rescanned the port and found out that they have closed telnet port completely!

**Comment by minhng99** [comment]
Yes, I do know what the telnet password is, also I do know that there are a lot of telnet-enabled ONU being publicly accessible on the Internet so i couldn't tell you, sorry.


There's no need to bruteforce for the password, it's right there if you know where to look for it

**Comment by raspiduino** [comment]
Ok thanks!
